name: Docker publish vizzu-dev-desktop

on:
    push:
        branches-ignore:
            - main
        paths:
            - '**/vizzu-dev-desktop'
            - '**/docker-vizzu-dev-desktop.yml'

jobs:
    publish:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 1

            - name: Login to Docker
              run: echo ${{ secrets.VIZZUHQ_DOCKER_API }} | docker login -u ${{ secrets.VIZZUHQ_DOCKER_USER }} --password-stdin

            - name: Build and Publish
              run: |
                  IMAGE="vizzu-dev-desktop"
                  IMAGE_NAME="vizzu/$IMAGE:0.10"
                  docker build -t $IMAGE_NAME -f tools/ci/docker/$IMAGE .
                  docker push $IMAGE_NAME
